version: 2.1
jobs:
  build_frontend:

  build_backend:
  
  test_frontend:
    docker: 
    steps:
      - checkout
      - restore_cache:
      - run:
          name: Run frontend test
          command:

workflows:
  my_workflow:
    jobs:
      - build_frontend
      - build_backend
      - test_frontend:
          requires:[build_frontend]
      - test_backend:
          requires: [build_backend]
      
            